version: 2.1

jobs:
  build:
    docker:
      - image: amazoncorretto:17.0.3
    steps:
      - run: |
          yum upgrade -y
          yum localinstall -y --nogpgcheck https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm
          yum install -y --nogpgcheck mysql-community-client tar unzip git
      - run: |
          git version
      - run: |
          mysql --version
